name: H2O_nf_random

# _, limb, _,  divertisy, prediction, RECON_mm, prior_lkh, history, angle
lambdas: [0, 500.0, 0, 160, 2.0, 1.0, 0.01, 50, 100 ]  # h36m from STARS
# lambdas: [0, 50, 0, 32, 2, 1, 0.002, 10, 10]  # humaneva from STARS

# lambdas: [ 0, 50.0, 0, 16, 8.0, 4.0, 0.002, 10, 10] # from SLD humaneva

dataset: H2O

STEN_cfg:
    z_dim: 16
    nz: 128
    t_his: 20
    t_pred: 80
    dropout: 0.1
    nk: 10
    nk1: 2
    nk2: 5

    lr: 1.e-2
    batch_size: 4096
    save_model_interval: 10
    num_epoch: 25
    num_epoch_fix: 5
    num_data_sample: 200000 
    normalize_data: False

    specs:
        num_flow_layer: 3
        n_pre: 20 # DCT first 20
        multimodal_path: dataset/H2O_multi_modal/t_his20_1_thre0.050_t_pred80_thre0.100_index_subAll_random.npz
        data_candi_path: dataset/H2O_multi_modal/data_multimodal_t_his20_t_pred80_skiprate15_random.npz

# diffusion model
RDGN_cfg:
    lr: 3.e-4
    diff_latent_dim: 512  # 512 1280

    batch_size: 16
    num_data_sample: 2000
    noise_steps: 1000
    ddim_timesteps: 4
    mod_test: 1.0

    mlp_ratio: 2
    dropout: 0.2
    activation: 'gelu'
    num_layers: 5  # 8
    num_heads: 8
    DM_scheduler: 'linear'
    prompt_len: 10
    num_epoch: 500  # 501
    save_model_interval: 10

# vis
scale: 9