name: HO3D_nf_random

# _, limb, _,  divertisy, prediction, RECON_mm, prior_lkh, history, angle
lambdas: [0, 40, 0, 80, 4, 2, 0.002, 10, 5]

dataset: HO3D

STEN_cfg:
    z_dim: 16
    nz: 128
    t_his: 20
    t_pred: 80
    dropout: 0.1
    nk: 10
    nk1: 2
    nk2: 5

    lr: 1.e-2
    batch_size: 4096
    save_model_interval: 10
    num_epoch: 25
    num_epoch_fix: 5
    num_data_sample: 200000 
    normalize_data: False

    specs:
        num_flow_layer: 3
        n_pre: 20 
        multimodal_path: dataset/HO3D_multi_modal/t_his20_1_thre0.050_t_pred80_thre0.100_index_subAll_random.npz
        data_candi_path: dataset/HO3D_multi_modal/data_multimodal_t_his20_t_pred80_skiprate15_random.npz

# diffusion model
RDGN_cfg:
    lr: 2.e-4                    
    diff_latent_dim: 768         
    features: 320                

    batch_size: 64               
    num_data_sample: 10000       
    noise_steps: 1000
    ddim_timesteps: 10           
    mod_train: 0.8               

    mlp_ratio: 3                 
    dropout: 0.15                
    activation: 'gelu'
    num_layers: 4                
    num_heads: 4                 
    DM_scheduler: 'linear'
    prompt_len: 10
    num_epoch: 500 
    save_model_interval: 50

# skeleton scale
scale: 9